import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

async function seedThuoc() {
  try {
    // Thêm dữ liệu mẫu cho thuốc VSS
    const thuocVSS = await prisma.thuocVSS.createMany({
      data: [
        {
          tenThuoc: "Paracetamol 500mg",
          hoatChat: "Paracetamol",
          hamLuong: "500mg",
          gdklh: "VD-12345-20",
          duongDung: "Uống",
          dangBaoChe: "Viên nén",
          tenCoSoSanXuat: "Công ty Dược phẩm ABC",
          nuocSanXuat: "Việt Nam",
          quyCachDongGoi: "Hộp 10 vỉ x 10 viên",
          donViTinh: "Hộp",
          soLuong: "1000",
          donGia: "15000",
          nhomThuoc: "Thuốc giảm đau, hạ sốt",
          tenDonViTrungThau: "Bệnh viện Đa khoa Tỉnh",
          tinh: "Hà Nội",
          tenNhaThau: "Công ty TNHH Dược phẩm XYZ",
          soQuyetDinh: "123/QĐ-BYT",
          ngayCongBo: new Date("2024-01-15"),
          loaiThuoc: "Thuốc kê đơn",
          maTT: "TT001",
          maDuongDung: "DD01",
        },
        {
          tenThuoc: "Amoxicillin 500mg",
          hoatChat: "Amoxicillin",
          hamLuong: "500mg",
          gdklh: "VD-12346-20",
          duongDung: "Uống",
          dangBaoChe: "Viên nang",
          tenCoSoSanXuat: "Công ty Dược phẩm DEF",
          nuocSanXuat: "Việt Nam",
          quyCachDongGoi: "Hộp 10 vỉ x 10 viên",
          donViTinh: "Hộp",
          soLuong: "500",
          donGia: "45000",
          nhomThuoc: "Kháng sinh",
          tenDonViTrungThau: "Bệnh viện Trung ương",
          tinh: "Hà Nội",
          tenNhaThau: "Công ty CP Dược Hà Tây",
          soQuyetDinh: "124/QĐ-BYT",
          ngayCongBo: new Date("2024-01-20"),
          loaiThuoc: "Thuốc kê đơn",
          maTT: "TT002",
          maDuongDung: "DD01",
        },
        {
          tenThuoc: "Vitamin C 500mg",
          hoatChat: "Acid ascorbic",
          hamLuong: "500mg",
          gdklh: "VD-12347-20",
          duongDung: "Uống",
          dangBaoChe: "Viên sủi",
          tenCoSoSanXuat: "Công ty Dược phẩm GHI",
          nuocSanXuat: "Đức",
          quyCachDongGoi: "Tuýp 20 viên",
          donViTinh: "Tuýp",
          soLuong: "2000",
          donGia: "35000",
          nhomThuoc: "Vitamin và khoáng chất",
          tenDonViTrungThau: "Bệnh viện Nhi Trung ương",
          tinh: "Hồ Chí Minh",
          tenNhaThau: "Công ty TNHH Dược Quốc Tế",
          soQuyetDinh: "125/QĐ-BYT",
          ngayCongBo: new Date("2024-02-01"),
          loaiThuoc: "Thuốc không kê đơn",
          maTT: "TT003",
          maDuongDung: "DD01",
        },
        {
          tenThuoc: "Omeprazole 20mg",
          hoatChat: "Omeprazole",
          hamLuong: "20mg",
          gdklh: "VD-12348-20",
          duongDung: "Uống",
          dangBaoChe: "Viên nang",
          tenCoSoSanXuat: "Công ty Dược phẩm JKL",
          nuocSanXuat: "Ấn Độ",
          quyCachDongGoi: "Hộp 3 vỉ x 10 viên",
          donViTinh: "Hộp",
          soLuong: "800",
          donGia: "55000",
          nhomThuoc: "Thuốc tiêu hóa",
          tenDonViTrungThau: "Bệnh viện Bạch Mai",
          tinh: "Hà Nội",
          tenNhaThau: "Công ty CP Dược phẩm Việt",
          soQuyetDinh: "126/QĐ-BYT",
          ngayCongBo: new Date("2024-02-10"),
          loaiThuoc: "Thuốc kê đơn",
          maTT: "TT004",
          maDuongDung: "DD01",
        },
        {
          tenThuoc: "Cefixime 200mg",
          hoatChat: "Cefixime",
          hamLuong: "200mg",
          gdklh: "VD-12349-20",
          duongDung: "Uống",
          dangBaoChe: "Viên nang",
          tenCoSoSanXuat: "Công ty Dược phẩm MNO",
          nuocSanXuat: "Thái Lan",
          quyCachDongGoi: "Hộp 2 vỉ x 10 viên",
          donViTinh: "Hộp",
          soLuong: "600",
          donGia: "85000",
          nhomThuoc: "Kháng sinh",
          tenDonViTrungThau: "Bệnh viện 108",
          tinh: "Hà Nội",
          tenNhaThau: "Công ty TNHH Dược phẩm Á Châu",
          soQuyetDinh: "127/QĐ-BYT",
          ngayCongBo: new Date("2024-02-15"),
          loaiThuoc: "Thuốc kê đơn",
          maTT: "TT005",
          maDuongDung: "DD01",
        },
      ],
    });

    console.log(`Đã thêm ${thuocVSS.count} thuốc VSS`);

    // Thêm dữ liệu mẫu cho thuốc MSC
    const thuocMSC = await prisma.thuocMSC.createMany({
      data: [
        {
          tenThuoc: "Metformin 500mg",
          hoatChat: "Metformin HCl",
          hamLuong: "500mg",
          gdklh: "VD-22345-20",
          duongDung: "Uống",
          dangBaoChe: "Viên nén bao phim",
          hanDung: "36 tháng",
          tenCoSoSanXuat: "Công ty Dược phẩm PQR",
          nuocSanXuat: "Việt Nam",
          quyCachDongGoi: "Hộp 10 vỉ x 10 viên",
          donViTinh: "Hộp",
          soLuong: "1500",
          donGia: "25000",
          nhomThuoc: "Thuốc điều trị đái tháo đường",
          maTBMT: "TBMT-2024-001",
          tenChuDauTu: "Sở Y tế Hà Nội",
          hinhThucLCNT: "Đấu thầu rộng rãi",
          ngayDangTai: new Date("2024-01-10"),
          soQuyetDinh: "201/QĐ-SYT",
          ngayBanHanhQuyetDinh: new Date("2024-01-25"),
          soNhaThauThamDu: "5",
          diaDiem: "Hà Nội",
        },
        {
          tenThuoc: "Atorvastatin 20mg",
          hoatChat: "Atorvastatin",
          hamLuong: "20mg",
          gdklh: "VD-22346-20",
          duongDung: "Uống",
          dangBaoChe: "Viên nén bao phim",
          hanDung: "36 tháng",
          tenCoSoSanXuat: "Công ty Dược phẩm STU",
          nuocSanXuat: "Ấn Độ",
          quyCachDongGoi: "Hộp 3 vỉ x 10 viên",
          donViTinh: "Hộp",
          soLuong: "1000",
          donGia: "65000",
          nhomThuoc: "Thuốc điều trị rối loạn lipid máu",
          maTBMT: "TBMT-2024-002",
          tenChuDauTu: "Bệnh viện Tim Hà Nội",
          hinhThucLCNT: "Chỉ định thầu",
          ngayDangTai: new Date("2024-01-15"),
          soQuyetDinh: "202/QĐ-BVTH",
          ngayBanHanhQuyetDinh: new Date("2024-01-30"),
          soNhaThauThamDu: "3",
          diaDiem: "Hà Nội",
        },
        {
          tenThuoc: "Losartan 50mg",
          hoatChat: "Losartan potassium",
          hamLuong: "50mg",
          gdklh: "VD-22347-20",
          duongDung: "Uống",
          dangBaoChe: "Viên nén bao phim",
          hanDung: "24 tháng",
          tenCoSoSanXuat: "Công ty Dược phẩm VWX",
          nuocSanXuat: "Hàn Quốc",
          quyCachDongGoi: "Hộp 3 vỉ x 10 viên",
          donViTinh: "Hộp",
          soLuong: "800",
          donGia: "45000",
          nhomThuoc: "Thuốc điều trị cao huyết áp",
          maTBMT: "TBMT-2024-003",
          tenChuDauTu: "Bệnh viện Đa khoa Tỉnh",
          hinhThucLCNT: "Đấu thầu rộng rãi",
          ngayDangTai: new Date("2024-02-01"),
          soQuyetDinh: "203/QĐ-BVT",
          ngayBanHanhQuyetDinh: new Date("2024-02-15"),
          soNhaThauThamDu: "7",
          diaDiem: "Hồ Chí Minh",
        },
        {
          tenThuoc: "Insulin Glargine 100IU/ml",
          hoatChat: "Insulin Glargine",
          hamLuong: "100IU/ml",
          gdklh: "VD-22348-20",
          duongDung: "Tiêm dưới da",
          dangBaoChe: "Dung dịch tiêm",
          hanDung: "30 tháng",
          tenCoSoSanXuat: "Công ty Dược phẩm YZA",
          nuocSanXuat: "Pháp",
          quyCachDongGoi: "Hộp 5 bút tiêm",
          donViTinh: "Hộp",
          soLuong: "300",
          donGia: "850000",
          nhomThuoc: "Thuốc điều trị đái tháo đường",
          maTBMT: "TBMT-2024-004",
          tenChuDauTu: "Bệnh viện Nội tiết Trung ương",
          hinhThucLCNT: "Chỉ định thầu",
          ngayDangTai: new Date("2024-02-05"),
          soQuyetDinh: "204/QĐ-BVNT",
          ngayBanHanhQuyetDinh: new Date("2024-02-20"),
          soNhaThauThamDu: "2",
          diaDiem: "Hà Nội",
        },
        {
          tenThuoc: "Amlodipine 5mg",
          hoatChat: "Amlodipine besilate",
          hamLuong: "5mg",
          gdklh: "VD-22349-20",
          duongDung: "Uống",
          dangBaoChe: "Viên nén",
          hanDung: "36 tháng",
          tenCoSoSanXuat: "Công ty Dược phẩm BCD",
          nuocSanXuat: "Việt Nam",
          quyCachDongGoi: "Hộp 10 vỉ x 10 viên",
          donViTinh: "Hộp",
          soLuong: "2000",
          donGia: "32000",
          nhomThuoc: "Thuốc điều trị cao huyết áp",
          maTBMT: "TBMT-2024-005",
          tenChuDauTu: "Sở Y tế TP.HCM",
          hinhThucLCNT: "Đấu thầu rộng rãi",
          ngayDangTai: new Date("2024-02-10"),
          soQuyetDinh: "205/QĐ-SYT-HCM",
          ngayBanHanhQuyetDinh: new Date("2024-02-25"),
          soNhaThauThamDu: "8",
          diaDiem: "Hồ Chí Minh",
        },
      ],
    });

    console.log(`Đã thêm ${thuocMSC.count} thuốc MSC`);

    console.log("\n✅ Seed dữ liệu mẫu thành công!");
    console.log("\nBây giờ bạn có thể:");
    console.log("1. Truy cập trang VSS để xem dữ liệu thuốc VSS");
    console.log("2. Truy cập trang MSC để xem dữ liệu thuốc MSC");
  } catch (error) {
    console.error("Lỗi khi seed dữ liệu:", error);
  } finally {
    await prisma.$disconnect();
  }
}

seedThuoc();





